import{neon}from"@neondatabase/serverless";import{hashAdminToken}from"./admin-auth";import type{CreatorProductSubmission}from"./creator-service";
const db=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");return neon(process.env.DATABASE_URL)};
export type CreatorIdentity={id:string;email:string;handle:string;displayName:string;status:string};
export async function createCreatorDb(profile:{email:string;handle:string;displayName:string}){const rows=await db().query("INSERT INTO creator_accounts(email,handle,display_name) VALUES($1,$2,$3) ON CONFLICT(email) DO UPDATE SET handle=excluded.handle,display_name=excluded.display_name,updated_at=now() RETURNING *",[profile.email,profile.handle,profile.displayName]);return rows[0]}
export async function createCreatorInviteDb(creatorId:string,rawToken:string){await db().transaction(tx=>[tx.query("UPDATE creator_invites SET consumed_at=now() WHERE creator_account_id=$1 AND consumed_at IS NULL",[creatorId]),tx.query("INSERT INTO creator_invites(creator_account_id,token_hash,expires_at) VALUES($1,$2,now()+interval '24 hours')",[creatorId,hashAdminToken(rawToken)])])}
export async function exchangeCreatorInviteDb(invite:string,session:string):Promise<CreatorIdentity>{const rows=await db().query("SELECT * FROM exchange_creator_invite($1,$2,now()+interval '30 days')",[hashAdminToken(invite),hashAdminToken(session)]) as Array<{creator_id:string;email:string;handle:string;display_name:string;status:string}>;if(!rows[0])throw new Error("Creator invitation is invalid or expired");return{id:rows[0].creator_id,email:rows[0].email,handle:rows[0].handle,displayName:rows[0].display_name,status:rows[0].status}}
export async function getCreatorSessionDb(session:string):Promise<CreatorIdentity|null>{const rows=await db().query("UPDATE creator_sessions s SET last_seen_at=now() FROM creator_accounts c WHERE s.creator_account_id=c.id AND s.token_hash=$1 AND s.expires_at>now() AND c.status<>'closed' RETURNING c.id,c.email,c.handle,c.display_name,c.status",[hashAdminToken(session)]) as Array<{id:string;email:string;handle:string;display_name:string;status:string}>;return rows[0]?{id:rows[0].id,email:rows[0].email,handle:rows[0].handle,displayName:rows[0].display_name,status:rows[0].status}:null}
export async function revokeCreatorSessionDb(session:string){await db().query("DELETE FROM creator_sessions WHERE token_hash=$1",[hashAdminToken(session)])}
export async function submitCreatorProductDb(creatorId:string,input:CreatorProductSubmission){const rows=await db().query("INSERT INTO creator_product_submissions(creator_account_id,draft,social_post_ids,status) SELECT id,$2::jsonb,$3::uuid[],'pending' FROM creator_accounts WHERE id=$1 AND status IN('pending','approved') RETURNING id",[creatorId,JSON.stringify(input),input.socialPostIds]);if(!rows[0])throw new Error("Creator account cannot submit products");return rows[0]}
export async function getCreatorDashboardDb(creatorId:string){const sql=db();const[account,submissions,fulfillments,earnings,payouts,posts]=await Promise.all([sql.query("SELECT id,email,handle,display_name,stripe_onboarding_status,status FROM creator_accounts WHERE id=$1",[creatorId]),sql.query("SELECT * FROM creator_product_submissions WHERE creator_account_id=$1 ORDER BY submitted_at DESC",[creatorId]),sql.query(`SELECT f.*,oi.product_name,oi.variant_label,oi.quantity,o.order_number,o.shipping_city,o.shipping_state,o.shipping_postal_code,o.shipping_country FROM order_item_fulfillments f JOIN order_items oi ON oi.id=f.order_item_id JOIN orders o ON o.id=f.order_id WHERE f.creator_account_id=$1 ORDER BY f.created_at DESC`,[creatorId]),sql.query("SELECT status,sum(creator_net_cents)::integer amount_cents,count(*)::integer items FROM creator_earnings WHERE creator_account_id=$1 GROUP BY status",[creatorId]),sql.query("SELECT * FROM creator_payouts WHERE creator_account_id=$1 ORDER BY created_at DESC",[creatorId]),sql.query("SELECT * FROM social_posts WHERE lower(creator_handle)=lower((SELECT handle FROM creator_accounts WHERE id=$1)) ORDER BY created_at DESC",[creatorId])]);return{account:account[0],submissions,fulfillments,earnings,payouts,posts}}
export async function reviewCreatorSubmissionDb(submissionId:string,status:"approved"|"rejected"|"changes_requested",notes:string,actor:string){const sql=db();const rows=await sql.query("SELECT s.*,c.status creator_status FROM creator_product_submissions s JOIN creator_accounts c ON c.id=s.creator_account_id WHERE s.id=$1 AND s.status='pending'",[submissionId]);if(!rows[0])throw new Error("Pending creator submission not found");if(status!=="approved"){await sql.query("UPDATE creator_product_submissions SET status=$2,review_notes=$3,reviewed_at=now(),reviewed_by=$4 WHERE id=$1",[submissionId,status,notes,actor]);return{status}}
 const draft=rows[0].draft as CreatorProductSubmission;const media=await sql.query("SELECT id,media_url,media_alt FROM social_posts WHERE id=$1 AND status='approved' AND rights_confirmed AND media_url IS NOT NULL",[draft.primarySocialPostId]);if(!media[0])throw new Error("Primary post must be rights-approved and have reviewed media");const approved=await sql.query("SELECT count(*)::integer count FROM social_posts WHERE id=ANY($1::uuid[]) AND status='approved' AND rights_confirmed",[draft.socialPostIds]);if(Number(approved[0].count)!==draft.socialPostIds.length)throw new Error("Every associated post must be rights-approved");const p=draft.product;await sql.transaction(tx=>[
 tx.query(`INSERT INTO products(id,slug,name,brand,category,description,currency,image_url,image_alt,color,featured,active,seller_type,creator_account_id,fulfillment_model,review_status,platform_fee_bps,primary_social_post_id)
 VALUES($1,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,true,'creator',$11,'creator_dropship','approved',$12,$13) ON CONFLICT(id) DO UPDATE SET name=excluded.name,brand=excluded.brand,category=excluded.category,description=excluded.description,currency=excluded.currency,image_url=excluded.image_url,image_alt=excluded.image_alt,color=excluded.color,featured=excluded.featured,active=true,seller_type='creator',creator_account_id=excluded.creator_account_id,fulfillment_model='creator_dropship',review_status='approved',platform_fee_bps=excluded.platform_fee_bps,primary_social_post_id=excluded.primary_social_post_id,delinquent_at=NULL,hidden_reason=NULL,updated_at=now()`,[p.id,p.name,p.brand,p.category,p.description,p.currency,media[0].media_url,media[0].media_alt??p.imageAlt,p.color,p.featured,rows[0].creator_account_id,draft.platformFeeBps,draft.primarySocialPostId]),
 ...p.variants.map(v=>tx.query("INSERT INTO product_variants(id,product_id,sku,label,price_cents,inventory,weight_grams,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,label=excluded.label,price_cents=excluded.price_cents,weight_grams=excluded.weight_grams,active=excluded.active,updated_at=now()",[v.id,p.id,v.sku,v.label,v.priceCents,v.inventory,v.weightGrams,v.active])),
 ...draft.socialPostIds.map(id=>tx.query("INSERT INTO product_social_posts(product_id,social_post_id,relationship,confidence,public) VALUES($1,$2,'submitted',1,true) ON CONFLICT(product_id,social_post_id) DO UPDATE SET public=true",[p.id,id])),
 tx.query("UPDATE creator_product_submissions SET product_id=$2,status='approved',review_notes=$3,reviewed_at=now(),reviewed_by=$4 WHERE id=$1",[submissionId,p.id,notes,actor]),
 tx.query("UPDATE creator_accounts SET status='approved',updated_at=now() WHERE id=$1 AND status='pending'",[rows[0].creator_account_id]),
 tx.query("INSERT INTO audit_events(actor,action,entity_type,entity_id,metadata) VALUES($1,'creator_product.approved','creator_submission',$2,jsonb_build_object('productId',$3::text))",[actor,submissionId,p.id])
 ]);return{status,productId:p.id}}
export async function submitCreatorTrackingDb(creatorId:string,input:{fulfillmentId:string;carrier:string;trackingNumber:string;trackingUrl:string}){const rows=await db().query("SELECT submit_creator_tracking($1,$2,$3,$4,$5) id",[input.fulfillmentId,creatorId,input.carrier,input.trackingNumber,input.trackingUrl]);if(!rows[0])throw new Error("Tracking submission failed");return rows[0]}
export async function getCreatorAccountDb(id:string){const rows=await db().query("SELECT * FROM creator_accounts WHERE id=$1",[id]);return rows[0]??null}
export async function markCreatorFulfillmentDeliveredDb(id:string,actor:string,deliveredAt?:string){const rows=await db().query("SELECT mark_creator_fulfillment_delivered($1,$2,$3) id",[id,actor,deliveredAt??new Date().toISOString()]);return rows[0]}
export async function updateCreatorStripeDb(id:string,stripeAccountId:string,status:"pending"|"enabled"|"restricted"|"disabled"){const rows=await db().query("UPDATE creator_accounts SET stripe_account_id=$2,stripe_onboarding_status=$3,updated_at=now() WHERE id=$1 RETURNING *",[id,stripeAccountId,status]);return rows[0]}
