import{neon}from"@neondatabase/serverless";import Stripe from"stripe";
const db=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL is required");return neon(process.env.DATABASE_URL)};
export async function queueDelinquentRefundsDb(now=new Date()){return await db().query("SELECT * FROM queue_delinquent_creator_refunds($1)",[now.toISOString()]) as Array<{refund_request_id:string;order_id:string;amount_cents:number}>}
export async function listQueuedRefundsDb(){return await db().query(`SELECT r.id,r.order_id,r.amount_cents,o.stripe_payment_intent_id FROM refund_requests r JOIN orders o ON o.id=r.order_id WHERE r.status IN('queued','failed') AND r.attempt_count<10 ORDER BY r.created_at`) as Array<{id:string;order_id:string;amount_cents:number;stripe_payment_intent_id:string}>}
export async function markRefundAttemptDb(id:string,status:"processing"|"submitted"|"failed",details:{stripeRefundId?:string;error?:string}={}){await db().query("UPDATE refund_requests SET status=$2,attempt_count=attempt_count+CASE WHEN $2='processing' THEN 1 ELSE 0 END,stripe_refund_id=coalesce($3,stripe_refund_id),last_error=$4,updated_at=now() WHERE id=$1",[id,status,details.stripeRefundId??null,details.error??null])}
export async function finalizeMarketplaceRefundDb(eventId:string,refundId:string,paymentIntentId:string,status:string,requestId:string|null){const rows=await db().query(`WITH event AS(INSERT INTO payment_events(provider,event_id,event_type,payload_sha256) VALUES('stripe',$1,'refund.updated','verified') ON CONFLICT DO NOTHING RETURNING event_id),changed AS(
 UPDATE refund_requests SET status=CASE WHEN $4='succeeded' THEN 'succeeded' ELSE 'failed' END,stripe_refund_id=$2,last_error=CASE WHEN $4='failed' THEN 'Stripe reported refund failure' END,updated_at=now()
 WHERE (id::text=$5 OR stripe_refund_id=$2) AND EXISTS(SELECT 1 FROM event) RETURNING id,order_id,status
),fulfillments AS(UPDATE order_item_fulfillments SET status=CASE WHEN $4='succeeded' THEN 'refunded' ELSE 'refund_queued' END,updated_at=now() WHERE id IN(SELECT fulfillment_id FROM refund_request_items WHERE refund_request_id IN(SELECT id FROM changed))),order_state AS(
 UPDATE orders o SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM order_item_fulfillments f WHERE f.order_id=o.id AND f.status<>'refunded') THEN 'refunded' ELSE o.status END,updated_at=now() WHERE id IN(SELECT order_id FROM changed)
) SELECT order_id FROM changed`,[eventId,refundId,paymentIntentId,status,requestId]);return rows[0]??null}
export async function releaseAndQueuePayoutsDb(){const rows=await db().query("SELECT * FROM queue_creator_payouts(now())");return rows.length}
export async function listQueuedPayoutsDb(){return await db().query("SELECT p.id,p.amount_cents,c.stripe_account_id FROM creator_payouts p JOIN creator_accounts c ON c.id=p.creator_account_id WHERE p.status IN('queued','failed') AND p.attempt_count<10 AND c.status='approved' AND c.stripe_onboarding_status='enabled' ORDER BY p.created_at") as Array<{id:string;amount_cents:number;stripe_account_id:string}>}
export async function runMarketplaceAutomation(){const queued=await queueDelinquentRefundsDb();if(!process.env.STRIPE_SECRET_KEY)return{queuedRefunds:queued.length,submittedRefunds:0,payouts:0,configured:false};const stripe=new Stripe(process.env.STRIPE_SECRET_KEY);let submittedRefunds=0;for(const refund of await listQueuedRefundsDb()){try{await markRefundAttemptDb(refund.id,"processing");const result=await stripe.refunds.create({payment_intent:refund.stripe_payment_intent_id,amount:refund.amount_cents,metadata:{refund_request_id:refund.id,reason:"creator_tracking_delinquent"}},{idempotencyKey:`creator-delinquency-${refund.id}`});await markRefundAttemptDb(refund.id,"submitted",{stripeRefundId:result.id});submittedRefunds++}catch(error){await markRefundAttemptDb(refund.id,"failed",{error:error instanceof Error?error.message:"Stripe refund failed"})}}
 await releaseAndQueuePayoutsDb();let payouts=0;for(const payout of await listQueuedPayoutsDb()){try{await db().query("UPDATE creator_payouts SET status='processing',attempt_count=attempt_count+1,last_error=NULL WHERE id=$1",[payout.id]);const transfer=await stripe.transfers.create({amount:payout.amount_cents,currency:"usd",destination:payout.stripe_account_id,metadata:{creator_payout_id:payout.id}},{idempotencyKey:`creator-payout-${payout.id}`});await db().query("UPDATE creator_payouts SET status='submitted',stripe_transfer_id=$2,updated_at=now() WHERE id=$1",[payout.id,transfer.id]);payouts++}catch(error){await db().query("UPDATE creator_payouts SET status='failed',last_error=$2 WHERE id=$1",[payout.id,error instanceof Error?error.message:"Stripe transfer failed"]);}}
 return{queuedRefunds:queued.length,submittedRefunds,payouts,configured:true}}

export async function finalizeCreatorPayoutDb(eventId:string,transferId:string,payoutId:string,status:"paid"|"failed"){const rows=await db().query(`WITH event AS(INSERT INTO payment_events(provider,event_id,event_type,payload_sha256) VALUES('stripe',$1,$4,'verified') ON CONFLICT DO NOTHING RETURNING event_id),changed AS(UPDATE creator_payouts SET status=$4,stripe_transfer_id=$2,paid_at=CASE WHEN $4='paid' THEN now() ELSE paid_at END,last_error=CASE WHEN $4='failed' THEN 'Stripe transfer reversed' END,updated_at=now() WHERE (id::text=$3 OR stripe_transfer_id=$2) AND EXISTS(SELECT 1 FROM event) RETURNING id),earnings AS(UPDATE creator_earnings SET status=CASE WHEN $4='paid' THEN 'paid' ELSE 'reversed' END,updated_at=now() WHERE id IN(SELECT earning_id FROM creator_payout_items WHERE payout_id IN(SELECT id FROM changed))) SELECT id FROM changed`,[eventId,transferId,payoutId,status]);return rows[0]??null}
