import{afterAll,describe,expect,it}from"vitest";
import{neon}from"@neondatabase/serverless";
import{processPaidCheckoutDb,saveCartDb}from"./postgres-store";
const sql=neon(process.env.DATABASE_URL!);
const suffix=crypto.randomUUID().slice(0,8),creatorId=crypto.randomUUID();
const productIds=[`creator-delinquent-${suffix}`,`creator-payout-${suffix}`],variantIds=productIds.map(x=>`${x}-one`),cartIds=[crypto.randomUUID(),crypto.randomUUID()];
const eventIds=[`evt_creator_${suffix}_1`,`evt_creator_${suffix}_2`],sessionIds=[`cs_creator_${suffix}_1`,`cs_creator_${suffix}_2`],paymentIds=[`pi_creator_${suffix}_1`,`pi_creator_${suffix}_2`];
const orderIds:string[]=[],fulfillmentIds:string[]=[],payoutIds:string[]=[],refundIds:string[]=[];
async function makeOrder(index:number,tax=0,shipping=0){await saveCartDb(cartIds[index],[{variantId:variantIds[index],quantity:1}]);const id=await processPaidCheckoutDb({eventId:eventIds[index],sessionId:sessionIds[index],paymentIntentId:paymentIds[index],cartId:cartIds[index],email:"creator-lifecycle@example.com",shippingCents:shipping,taxCents:tax,totalCents:10000+tax+shipping,address:{name:"Lifecycle Buyer",line1:"1 Test St",city:"Chicago",state:"IL",postalCode:"60601",country:"US"}});orderIds.push(id);return id}
afterAll(async()=>{if(payoutIds.length)await sql.query("DELETE FROM creator_payouts WHERE id=ANY($1::uuid[])",[payoutIds]);if(refundIds.length)await sql.query("DELETE FROM refund_requests WHERE id=ANY($1::uuid[])",[refundIds]);if(orderIds.length){await sql.query("DELETE FROM creator_earnings WHERE order_item_id IN(SELECT id FROM order_items WHERE order_id=ANY($1::uuid[]))",[orderIds]);await sql.query("DELETE FROM inventory_movements WHERE reference_id=ANY($1::text[])",[orderIds]);await sql.query("DELETE FROM orders WHERE id=ANY($1::uuid[])",[orderIds]);}await sql.query("DELETE FROM payment_events WHERE event_id=ANY($1::text[])",[eventIds]);await sql.query("DELETE FROM audit_events WHERE entity_id=ANY($1::text[]) OR entity_id=$2",[[...orderIds,...fulfillmentIds],creatorId]);await sql.query("DELETE FROM carts WHERE id=ANY($1::uuid[])",[cartIds]);await sql.query("DELETE FROM products WHERE id=ANY($1::text[])",[productIds]);await sql.query("DELETE FROM creator_accounts WHERE id=$1",[creatorId]);});
describe("creator dropship lifecycle",()=>{
 it("hides overdue inventory, queues one exact refund, and is idempotent",async()=>{
  await sql.query("INSERT INTO creator_accounts(id,email,handle,display_name,status,stripe_onboarding_status,stripe_account_id) VALUES($1,$2,$3,'Lifecycle Creator','approved','enabled',$4)",[creatorId,`creator-${suffix}@example.com`,`creator_${suffix}`,`acct_test_${suffix}`]);
  for(let i=0;i<2;i++){await sql.query("INSERT INTO products(id,slug,name,brand,category,description,image_url,image_alt,color,active,seller_type,creator_account_id,fulfillment_model,review_status,platform_fee_bps) VALUES($1,$1,$2,'Lifecycle Creator','Tops','Integration lifecycle product','https://example.com/product.jpg','Creator wearing lifecycle product','Black',true,'creator',$3,'creator_dropship','approved',2000)",[productIds[i],`Creator Test ${i+1}`,creatorId]);await sql.query("INSERT INTO product_variants(id,product_id,sku,label,price_cents,inventory,weight_grams) VALUES($1,$2,$3,'One size',10000,5,300)",[variantIds[i],productIds[i],`TEST-${suffix}-${i}`]);}
  const orderId=await makeOrder(0,1000,795);const fulfillment=(await sql.query("SELECT id FROM order_item_fulfillments WHERE order_id=$1",[orderId]))[0];fulfillmentIds.push(String(fulfillment.id));await sql.query("UPDATE order_item_fulfillments SET tracking_deadline_at=now()-interval '1 minute' WHERE id=$1",[fulfillment.id]);
  const queued=await sql.query("SELECT * FROM queue_delinquent_creator_refunds(now())");expect(queued).toHaveLength(1);expect(queued[0]).toMatchObject({order_id:orderId,amount_cents:11795});refundIds.push(String(queued[0].refund_request_id));
  const productRows=await sql.query("SELECT active,review_status,hidden_reason FROM products WHERE id=$1",[productIds[0]]);
  expect(productRows[0]).toMatchObject({active:false,review_status:"delinquent",hidden_reason:"Creator did not submit shipment tracking within 48 hours"});
  expect((await sql.query("SELECT status FROM order_item_fulfillments WHERE id=$1",[fulfillment.id]))[0].status).toBe("refund_queued");expect((await sql.query("SELECT status FROM creator_earnings WHERE order_item_id=(SELECT order_item_id FROM order_item_fulfillments WHERE id=$1)",[fulfillment.id]))[0].status).toBe("reversed");expect(await sql.query("SELECT * FROM queue_delinquent_creator_refunds(now())")).toHaveLength(0);
 });
 it("holds delivered earnings, queues one payout after the return window, and is idempotent",async()=>{
  const orderId=await makeOrder(1);const fulfillment=(await sql.query("SELECT id FROM order_item_fulfillments WHERE order_id=$1",[orderId]))[0];fulfillmentIds.push(String(fulfillment.id));await sql.query("SELECT submit_creator_tracking($1,$2,'UPS','1ZTEST','https://www.ups.com/track?loc=en_US&tracknum=1ZTEST')",[fulfillment.id,creatorId]);await sql.query("SELECT mark_creator_fulfillment_delivered($1,'integration-test',now()-interval '31 days')",[fulfillment.id]);
  const queued=await sql.query("SELECT * FROM queue_creator_payouts(now())");expect(queued).toHaveLength(1);expect(queued[0]).toMatchObject({creator_id:creatorId,amount_cents:8000});payoutIds.push(String(queued[0].payout_id));expect(await sql.query("SELECT * FROM queue_creator_payouts(now())")).toHaveLength(0);expect((await sql.query("SELECT status FROM creator_earnings WHERE order_item_id=(SELECT order_item_id FROM order_item_fulfillments WHERE id=$1)",[fulfillment.id]))[0].status).toBe("held");
 });
});
