"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Row=Record<string,unknown>;
export default function AdminConsole({admin,data}:{admin:{email:string;role:string};data:{products:Row[];orders:Row[];social:Row[];shipments:Row[];returns:Row[];purchaseOrders:Row[];supportRequests:Row[];creators:Row[];creatorSubmissions:Row[];fulfillments:Row[];refunds:Row[];earnings:Row[];payouts:Row[];audit:Row[]}}){
 const router=useRouter();
 const [section,setSection]=useState("catalog");const [message,setMessage]=useState("");
 async function action(url:string,body:unknown,method="POST",reload=true){setMessage("Saving…");const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setMessage(response.ok?"Saved.":result.error||"Action failed");if(response.ok&&reload)location.reload();return result;}
 async function logout(){await fetch("/api/admin/logout",{method:"POST"});router.push("/admin");router.refresh();}
 const sections:[[string,string],...Array<[string,string]>]=[["catalog","Catalog & inventory"],["creators","Creators & payouts"],["orders","Orders"],["social","Social evidence"],["shipments","Shipping & returns"],["support","Support"],["audit","Audit log"]];
 const grouped=Object.values(data.products.reduce<Record<string,Record<string,unknown>>>((all,row)=>{const key=String(row.id);const product=all[key]??={id:row.id,name:row.name,brand:row.brand,category:row.category,color:row.color,description:row.description,currency:row.currency,imageUrl:row.image_url,imageAlt:row.image_alt,featured:row.featured,active:row.active,variants:[]};(product.variants as unknown[]).push({id:row.variant_id,sku:row.sku,label:row.label,priceCents:row.price_cents,inventory:row.inventory,weightGrams:row.weight_grams,active:row.variant_active});all[key]=product;return all;},{}));
 return <main className="admin-shell"><header><div><p className="eyebrow">Fashion Social</p><h1>Operations</h1><span>{admin.email} · {admin.role}</span></div><button onClick={logout}>Sign out</button></header><nav>{sections.map(([id,label])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}>{label}</button>)}</nav>{message&&<p role="status" className="admin-message">{message}</p>}
 {section==="catalog"&&<section><h2>Catalog & inventory</h2><details className="admin-editor"><summary>Create product</summary><ProductJsonForm initial={{id:"new-product",name:"New Product",brand:"Fashion Social",category:"Category",color:"Black",description:"Describe materials, fit, and construction.",currency:"usd",imageUrl:"/products/new-product.jpg",imageAlt:"Product photograph",featured:false,active:false,variants:[{id:"new-product-s",sku:"FS-NEW-S",label:"S",priceCents:10000,inventory:0,weightGrams:500,active:true}]}} save={(value)=>action("/api/admin/products",value,"PUT")}/></details>{grouped.map(product=><details className="admin-editor" key={String(product.id)}><summary>Edit {String(product.name)}</summary><ProductJsonForm initial={product} save={(value)=>action("/api/admin/products",value,"PUT")}/></details>)}<h3>Stock adjustments</h3><div className="admin-table">{data.products.map((row)=><article key={String(row.variant_id)}><div><strong>{String(row.name)}</strong><span>{String(row.sku)} · {String(row.label)} · ${(Number(row.price_cents)/100).toFixed(2)}</span></div><b>{String(row.inventory)} in stock</b><form onSubmit={(e)=>{e.preventDefault();const form=new FormData(e.currentTarget);action("/api/admin/inventory",{variantId:row.variant_id,delta:Number(form.get("delta")),reason:form.get("reason")})}}><input name="delta" type="number" placeholder="± qty" required/><input name="reason" placeholder="Receiving, damage, correction" required/><button>Adjust</button></form></article>)}</div></section>}
 {section==="creators"&&<section><h2>Creators, dropship exceptions & payouts</h2><h3>Invite a creator</h3><form className="admin-inline-form" onSubmit={async e=>{e.preventDefault();const result=await action("/api/admin/creators",Object.fromEntries(new FormData(e.currentTarget)),"POST",false);if(result.inviteUrl)setMessage(`Copy this one-time link now: ${result.inviteUrl}`)}}><input name="email" type="email" placeholder="Creator email" required/><input name="handle" placeholder="@handle" required/><input name="displayName" placeholder="Display name" required/><button>Create invitation</button></form><h3>Creator accounts</h3><pre>{JSON.stringify(data.creators,null,2)}</pre><h3>Product review queue</h3><div className="admin-table">{data.creatorSubmissions.map(row=><article key={String(row.id)}><div><strong>@{String(row.handle)} · {String(row.status)}</strong><span>{String(row.id)} · {new Date(String(row.submitted_at)).toLocaleString()}</span><details><summary>Submission</summary><pre>{JSON.stringify(row.draft,null,2)}</pre></details></div>{row.status==="pending"&&<div><button onClick={()=>action("/api/admin/creator-submissions",{id:row.id,status:"approved",notes:"Rights, media, pricing, and fulfillment reviewed"},"PATCH")}>Approve & publish</button><button onClick={()=>action("/api/admin/creator-submissions",{id:row.id,status:"changes_requested",notes:prompt("Requested changes")??"Changes required"},"PATCH")}>Request changes</button><button onClick={()=>action("/api/admin/creator-submissions",{id:row.id,status:"rejected",notes:prompt("Rejection reason")??"Rejected"},"PATCH")}>Reject</button></div>}</article>)}</div><h3>Tracking deadlines and exceptions</h3><div className="admin-table">{data.fulfillments.map(row=><article key={String(row.id)}><div><strong>{String(row.product_name)} · @{String(row.handle??"Wornly")}</strong><span>{String(row.order_number)} · {String(row.status)} · deadline {String(row.tracking_deadline_at??"warehouse")}</span>{typeof row.tracking_url==="string"&&<a href={String(row.tracking_url)} target="_blank" rel="noreferrer">Track shipment ↗</a>}</div>{["tracking_submitted","in_transit"].includes(String(row.status))&&<button onClick={()=>action("/api/admin/creator-fulfillments",{id:row.id,deliveredAt:new Date().toISOString()},"PATCH")}>Confirm delivered</button>}</article>)}</div><h3>Refund queue</h3><pre>{JSON.stringify(data.refunds,null,2)}</pre><h3>Creator earnings</h3><pre>{JSON.stringify(data.earnings,null,2)}</pre><h3>Stripe payouts</h3><pre>{JSON.stringify(data.payouts,null,2)}</pre></section>}
 {section==="orders"&&<section><h2>Orders</h2><div className="admin-table">{data.orders.length?data.orders.map((row)=><article key={String(row.id)}><div><strong>{String(row.email)}</strong><span>{String(row.id)} · {new Date(String(row.created_at)).toLocaleString()}</span></div><b>{String(row.status)} · ${(Number(row.total_cents)/100).toFixed(2)}</b></article>):<p>No paid orders yet.</p>}</div></section>}
 {section==="social"&&<section><h2>Social evidence moderation</h2><p>Only official platform URLs with documented storefront-display rights can be approved. Engagement must identify its source and capture time.</p><h3>Submit evidence</h3><ProductJsonForm label="Social submission JSON" initial={{url:"https://www.instagram.com/p/POST_ID/",creatorHandle:"creator",productIds:["city-knit"],rightsConfirmed:true,rightsBasis:"Creator granted storefront display rights on YYYY-MM-DD"}} save={(value)=>action("/api/admin/social/submit",value)}/><h3>Moderation queue</h3><div className="admin-table">{data.social.length?data.social.map((row)=><article key={String(row.id)}><div><strong>{String(row.creator_handle||"Unattributed")}</strong><a href={String(row.canonical_url)} target="_blank" rel="noreferrer">{String(row.platform)} source ↗</a><span>{String(row.status)} · rights {String(row.rights_confirmed)}</span></div><div><button onClick={()=>action("/api/admin/social/moderate",{id:row.id,status:"approved"})}>Approve</button><button onClick={()=>action("/api/admin/social/moderate",{id:row.id,status:"rejected"})}>Reject</button></div></article>):<p>No submitted evidence.</p>}</div><h3>Add verified engagement snapshot</h3><ProductJsonForm label="Engagement snapshot JSON" initial={{socialPostId:"approved-post-uuid",likes:0,comments:0,views:0,source:"Official platform API or administrator-verified public count"}} save={(value)=>action("/api/admin/social/snapshot",value)}/></section>}
 {section==="shipments"&&<section><h2>Shipping, receiving & returns</h2><h3>Mark order shipped</h3><form className="admin-inline-form" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);action("/api/admin/shipments",Object.fromEntries(f))}}><input name="orderId" placeholder="Order UUID" required/><input name="carrier" placeholder="Carrier" required/><input name="service" placeholder="Service" required/><input name="trackingNumber" placeholder="Tracking number" required/><button>Record shipment</button></form><h3>Create purchase order</h3><ProductJsonForm label="Purchase order JSON" initial={{vendor:"Vendor name",expectedAt:new Date().toISOString().slice(0,10),items:[{variantId:"after-dark-blazer-xs",quantity:10,unitCostCents:5000}]}} save={(value)=>action("/api/admin/purchase-orders",value)}/><h3>Purchase orders</h3><pre>{JSON.stringify(data.purchaseOrders,null,2)}</pre><h3>Shipments</h3><pre>{JSON.stringify(data.shipments,null,2)}</pre><h3>Returns</h3><pre>{JSON.stringify(data.returns,null,2)}</pre></section>}
 {section==="support"&&<section><h2>Customer and rights support</h2><div className="admin-table">{data.supportRequests.map(row=><article key={String(row.id)}><div><strong>{String(row.category)} · {String(row.email)}</strong><span>{String(row.message)}</span></div><select aria-label={`Status for ${String(row.id)}`} value={String(row.status)} onChange={e=>action("/api/admin/support",{id:row.id,status:e.target.value},"PATCH")}><option value="open">Open</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></article>)}</div></section>}
 {section==="audit"&&<section><h2>Audit log</h2><div className="admin-table">{data.audit.map((row)=><article key={String(row.id)}><div><strong>{String(row.action)}</strong><span>{String(row.actor)} · {String(row.entity_type)} {String(row.entity_id)}</span></div><time>{new Date(String(row.created_at)).toLocaleString()}</time></article>)}</div></section>}
 </main>;
}

function ProductJsonForm({initial,save,label="Product JSON"}:{initial:Record<string,unknown>;save:(value:unknown)=>void;label?:string}){const [value,setValue]=useState(JSON.stringify(initial,null,2));return <form onSubmit={(event)=>{event.preventDefault();try{save(JSON.parse(value))}catch{alert("JSON is invalid")}}}><textarea aria-label={label} rows={18} value={value} onChange={(event)=>setValue(event.target.value)}/><button>Save</button></form>}
